[phases.setup]
nixPkgs = ["nodejs_20", "php83", "php83Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --include=dev",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear"
]

[start]
cmd = "php artisan migrate:fresh --force --seed && php -S 0.0.0.0:$PORT -t public"
