[phases.setup]
nixPkgs = ["nodejs_20", "php83", "php83Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --include=dev",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
